import { schema, table, t } from 'spacetimedb/server';

const spacetimedb = schema({
  room: table(
    { public: true },
    {
      id: t.string().primaryKey(),
      team_name: t.string(),
      host_identity: t.identity(),
      form_data: t.string(),
    }
  ),
  user: table(
    { public: true },
    {
      identity: t.identity().primaryKey(),
      name: t.string(),
      room_id: t.string(),
      is_host: t.bool(),
    }
  )
});
export default spacetimedb;

function generateRoomId(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  // Not using Math.random() as SpacetimeDB reducers must be deterministic
  // Wait, SpacetimeDB provides a deterministic random generator? 
  // Wait! Reducers MUST be deterministic in SpacetimeDB.
  // We should just use something else or allow the client to pass the RoomID.
  // Wait, I will use a simple fixed ID if this is a problem, or let the client generate the roomId and pass it.
  return "placeholder";
}
// Client passing the room ID is better.

export const createRoom = spacetimedb.reducer(
  { roomId: t.string(), teamName: t.string(), userName: t.string() },
  (ctx, { roomId, teamName, userName }) => {
    // roomId should be 6 characters (generated by frontend)
    
    const existing = ctx.db.room.id.find(roomId);
    if (existing) {
        throw new Error("Room already exists.");
    }

    ctx.db.room.insert({
      id: roomId,
      team_name: teamName,
      host_identity: ctx.sender,
      form_data: "{}",
    });
    
    // Check if user exists
    const existingUser = ctx.db.user.identity.find(ctx.sender);
    if (existingUser) {
        ctx.db.user.identity.update({
            ...existingUser,
            name: userName,
            room_id: roomId,
            is_host: true
        });
    } else {
        ctx.db.user.insert({
          identity: ctx.sender,
          name: userName,
          room_id: roomId,
          is_host: true,
        });
    }
  }
);

export const joinRoom = spacetimedb.reducer(
  { roomId: t.string(), userName: t.string() },
  (ctx, { roomId, userName }) => {
    const room = ctx.db.room.id.find(roomId);
    if (!room) {
      throw new Error(`Room ${roomId} not found.`);
    }
    
    const existingUser = ctx.db.user.identity.find(ctx.sender);
    if (existingUser) {
      ctx.db.user.identity.update({
         ...existingUser,
         name: userName,
         room_id: roomId,
         is_host: room.host_identity.isEqual(ctx.sender),
      });
    } else {
      ctx.db.user.insert({
        identity: ctx.sender,
        name: userName,
        room_id: roomId,
        is_host: room.host_identity.isEqual(ctx.sender),
      });
    }
  }
);

export const updateFormData = spacetimedb.reducer(
  { roomId: t.string(), formData: t.string() },
  (ctx, { roomId, formData }) => {
    const room = ctx.db.room.id.find(roomId);
    if (!room) {
      throw new Error(`Room ${roomId} not found.`);
    }
    
    if (!room.host_identity.isEqual(ctx.sender)) {
      throw new Error(`Only the host can update the form data.`);
    }
    
    ctx.db.room.id.update({
      ...room,
      form_data: formData,
    });
  }
);

export const onDisconnect = spacetimedb.clientDisconnected(ctx => {
  const user = ctx.db.user.identity.find(ctx.sender);
  if (user) {
    ctx.db.user.identity.delete(ctx.sender);
  }
});
