// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Room = __t.object("Room", {
  id: __t.string(),
  teamName: __t.string(),
  hostIdentity: __t.identity(),
  formData: __t.string(),
});
export type Room = __Infer<typeof Room>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  roomId: __t.string(),
  isHost: __t.bool(),
});
export type User = __Infer<typeof User>;

